services:
    pgdatabase:
      image: postgres:13
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=ny_taxi
      volumes:
        - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
      ports:
        - "5432:5432"
      networks:
        - taxi_network

    pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "8080:80"
      networks:
        - taxi_network

    ingestor:
      build: ./code
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=ny_taxi
      depends_on:
        - pgdatabase
      networks:
        - taxi_network

networks:
  taxi_network:
    driver: bridge